[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
rmt = { path = ".." }
serde = { version = "^1.0", features = ["derive"] }
log = "^0.4"
reqwest = { version = "^0.13", features = ["json"] }
actix-web = "4"
chrono = "*"